version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - varnamelen
    - wrapcheck
    - nonamedreturns
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - go.uber.org/fx/fxevent.Logger
        - go.uber.org/fx.Option
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      - linters:
        - lll
        source: "^//go:generate "
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard 
        - default
        - blank
        - dot
        - alias
        - localmodule
      custom-order: true

issues:
  fix: true
run:
  timeout: 5m
  relative-path-mode: gomod
