receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch: {}
  resource:
    attributes:
      - key: service.name
        value: app
        action: insert
      - key: service.namespace
        value: dev
        action: insert

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: sl
    send_timestamps: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]