# env is used to determine which deployment environment the app is running in.
env: "local"
# db_conn is the connection string for the database.
db_conn: "storage/sqlite_storage.db"
# http_server is the configuration for the http server.
http_server:
  port: ":8080"
# link_cache is the configuration for the link cache.
link_cache:
  # ttl - time to live in seconds.
  ttl: 600s
  type: "bigcache"
# shut_down_timeout is the time in seconds to wait for the server to shut down gracefully.
shut_down_timeout: 60s
metrics:
  port: "8081"
